version: '2'
services:
  server:
    build: ./server
    container_name: server
    restart: always
    command: npm start
    volumes:
      - ./server/config.js:/server/config.js
      - ./server/index.js:/server/index.js
      - ./server/server.js:/server/server.js
      - ./server/model:/server/model
      - ./server/graphql:/server/graphql
      - ./server/src:/server/src
    ports:
      - "10101:10101"
    links:
      - database
  database:
    container_name: database
    image: mongo
    volumes:
      - ./server/data:/data/db
    ports:
      - "27017:27017"